# Automatically generated by configure - do not modify
SRC_PATH=/workspaces/WaveVM_Frontier-X/wavevm-qemu/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
